services:
  localstack:
    container_name: localstack_s3
    image: localstack/localstack:3.8.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - S3_BUCKET=dealflow-local-bucket
    volumes:
      - ./localstack/init:/etc/localstack/init
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
