services:
  localstack:
    container_name: localstack_s3
    image: localstack/localstack:3.8.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
